language: java
jdk:
   - oraclejdk9
   
addons:
   sonarcloud:
      organization: AlessDea
      token:
         secure: "x90jb31NO0vtiLCyKM7WLPvd1yB7AajR5oWEYRVgEXOQjWjBRZmYjThIz/LdLikV6PGcly6WjgdbhaI1oDySA1MnYpTQO+otOiC9V1WWiRQN0iweSOD2GXpMj6oqq/RAfTmLXw+omko0juJFhnIH0VlHBmS6NmdKkLBXmrnhMKRrBlfaklNs+WjE9wXKm5MLGt0X2IATkfCTzP41AhBn2B/wOe/caM+6BPDjXFCuNueumMcsMzyGsHw6hy8sVXTL+VThldHU8aoIPYY9cF7JP5oylrijgbz44WEVGrSBh3HCwaz0HxB9ZTOwje2OTNPDfU0RIYOHJojS29QfeB7OKaIoEvUqqFxaZXhLm1ZXvENBR2d2gAPcyETo7CiynKGOg244ERHKF0ggJGNbtbSd3zTkEsWNuJaHM7EgyddJHD8T+BSNBB7wW3Job2yARS57k0tB6EnAZvSnWk0ERzRp7BOYLqcQw1RzavoliW3RfCBq3BIRvLmN8mwjy5YPCavSF+okf9OhhSGu8rUL8FFRtpo1K0N2rnLvySXJV/wEFG7++qHf9OhQXUoolzb7PgHpgkrlCLF5MBNEXWs95fhxFxJvzPraav1WX9GQJvJ5OAF1amWtQTdF8Ol17I6Ks/c5wy9SXgCZDTq+M7f9Y1mIX1goFIAux5bKP88MvFAs95k="
script: 
- ant build
- sonar-scanner
